### ISSUE TITLE
Server initialization failed: Scheme is missing

### ISSUE THREAD

**Issue by iDVB** [redhat-developer/vscode-yaml#215]
This is the error I get when starting VSCode and if I reinstall the extension. 

![image](https://user-images.githubusercontent.com/189506/63467724-1586a580-c434-11e9-8ad1-39cbb25ca994.png)

```
Server initialization failed.
  Message: Request initialize failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603 
```

![image](https://user-images.githubusercontent.com/189506/63467782-32bb7400-c434-11e9-8482-6d6ad1e02063.png)

**Comment by iDVB** [comment]
Even tried downgrading back to ...
![image](https://user-images.githubusercontent.com/189506/63468244-5fbc5680-c435-11e9-8d88-d4d3a7eab85e.png)

Uninstalled extension and restarted VSCode.
Still no luck.  
Literally in the middle of authoring a course in which I was showcasing this extension.
😢

**Comment by JPinkney** [comment]
I've just done a fresh install of vscode and a fresh install of the extension and I cannot reproduce. Can you set the yaml.trace.server setting to be verbose and the output dropdown to be YAML support and let me know what it shows

**Comment by iDVB** [comment]
> I've just done a fresh install of vscode and a fresh install of the extension and I cannot reproduce. Can you set the yaml.trace.server setting to be verbose and the output dropdown to be YAML support and let me know what it shows

Absolutely. Sorry though, I have no idea how to do any of that. 

I'm guessing the `yaml.trace.server` is just adding a line to my user.settings as....
`"yaml.trace.server": "verbose",`

no idea on the output though.

**Comment by JPinkney** [comment]
In your vscode user settings add "yaml.trace.server": "verbose" and then that's basically going to enable some logs for us.

Then when you're in this output view:
![image](https://user-images.githubusercontent.com/8839537/63469273-d22e3600-c437-11e9-95cc-64dde8c5757f.png)

where it says `Tasks` you'll need to click the dropdown and then select YAML support:
![image](https://user-images.githubusercontent.com/8839537/63469331-f38f2200-c437-11e9-9a1f-e82c62712d5f.png)

and then it should show a giant list of requests that are happening between the vscode-yaml extension and the yaml-language-server.

Do you still get the error when you aren't using this extension? Because the current picture you posted is just showing the logs for `Tasks`

**Comment by iDVB** [comment]
Yes I only get this error with the extension installed and if I open a yaml file.

Ok I think I figured how to do what you're asking.... but don't really see any helpful output.

I set verbose in the user settings.
Then I selected `Yaml Support` in the output dropdown. 
![image](https://user-images.githubusercontent.com/189506/63469570-8f209280-c438-11e9-80ce-33606ec96e4b.png)

this is the output before I select that from the dropdown...
```
[Trace - 5:19:48 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 6934,
    "rootPath": null,
    "rootUri": null,
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            }
        }
    },
    "trace": "verbose",
    "workspaceFolders": null
}


[Trace - 5:19:48 PM] Received response 'initialize - (0)' in 278ms. Request failed: Request initialize failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""} (-32603).
[Error - 5:19:48 PM] Server initialization failed.
  Message: Request initialize failed with message: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "null", query: "", fragment: ""}
  Code: -32603 
```

And this is after I select that dropdown...
![image](https://user-images.githubusercontent.com/189506/63469644-b7a88c80-c438-11e9-89fc-b8fa4bfe75ba.png)

**Comment by iDVB** [comment]
This is a video of what I'm seeing....
https://www.screencast.com/t/e04XxHZKQYF

**Comment by JPinkney** [comment]
I think I know what's happening. Basically in the logs 
```
"rootPath": null,
"rootUri": null
```
are both null and then 
```
 "workspaceFolders": null
```
is null as well so it looks like theres something wrong on the yaml language server side. I should be able to have a fix by tonight or tomorrow at the latest.

Just to double check something, are you trying to use the extension without opening up a workspace or project or folder in vscode? Because for now if you open up a folder and then edit a yaml file it should be working. 

The only way I could reproduce was by doing this:
![image](https://user-images.githubusercontent.com/8839537/63470374-8335d000-c43a-11e9-8afc-9b7d9ca77ee0.png)

**Comment by JPinkney** [comment]
Ah yeah, I just saw the video and it confirmed my suspicions. I should be able to fix that on the yaml language server and then i'll update this extension when that fix is available

**Comment by iDVB** [comment]
@JPinkney Ah... so it's a legit bug? How did it get introduced, I've had these working for a while now.  It seemed to have borked sometime within the last few days?

That would be AMAZING if you found a fix. Like I said, literally in the middle of screen recording for a course on CloudFormation and showing/suggesting this extension.

**Comment by iDVB** [comment]
> Just to double check something, are you trying to use the extension without opening up a workspace or project or folder in vscode? Because for now if you open up a folder and then edit a yaml file it should be working.

Weird... I thought I tested that.... but you're right... it doesn't error out with a folder open. 

However... it still does not seem to work with this extension....
https://marketplace.visualstudio.com/items?itemName=aws-scripting-guy.cform

I had this one working before... but now ever since I started getting this error... this extension also does not work.

**Comment by JPinkney** [comment]
I've released the new version with the fix and it seems to be working on my side. I'll quickly take a look into that other extension to see if I can find the error but no guarantees

**Comment by JPinkney** [comment]
I've just tested the other extension and it seems to be working fine for me. AFAIK it only contributes snippets and I don't know much about cloud formation so I've just been importing snippets and creating errors/testing the yaml

**Comment by iDVB** [comment]
Kk, thanks I’ll keep trying. 
Did you try it before or after your fix?
How can I get the fix?

**Comment by JPinkney** [comment]
I tried it after the fix. The fix should be available on the marketplace now, I've released version 0.5.1 of vscode-yaml. Inside of vscode if you go view -> extensions -> and then search `@installed vscode-yaml` in the search bar you should see 0.5.1 as the version. If your version is 0.5.0 then try reloading your vscode and then it should auto update.
![2019-08-21-185033_435x572_scrot](https://user-images.githubusercontent.com/8839537/63473755-9ea5d880-c444-11e9-8bf5-73139e414943.png)

**Comment by iDVB** [comment]
Fixed! Yup. Well it fixed the issue that was erroring. 
I still can't get that other extension to work anymore. 

Nw though I'll reach out them about that one. 
Thanks for your speedy action on this one though! 
Much appreciated!

**Comment by iDVB** [comment]
@JPinkney in case you want to chime in on this https://github.com/aws-scripting-guy/cform-VSCode/issues/43#issuecomment-524471904
