### ISSUE TITLE
Not processing YAML before sending for validation

### ISSUE THREAD

**Issue by JonathanWolfe** [redhat-developer/vscode-yaml#233]
I was getting some strange errors from my `.gitlab-ci.yml` about how `"Property << is not allowed"` when I realized that for validation the plugin is sending the raw document for validation, not the processed document (allowing for merges and such to be done).

#### Example that incorrectly throws validation errors:
```yaml
#----------------------------------------------------------------
# Templates
#----------------------------------------------------------------
.node-modules-cache: &node-modules-cache
    cache:
        key: $CI_PROJECT_NAME
        paths:
            - nodejs/node_modules
            - nodejs/{auth,dms,kpis}/node_modules # sub-project node_modules

#----------------------------------------------------------------
# Validate
#----------------------------------------------------------------
nodejs-tests:
    <<: *node-modules-cache
    stage: validate
    script:
        - cd nodejs
        - npm install
        - npm run test:coverage
    artifacts:
        expire_in: 1 day
        paths:
            - nodejs/coverage
```

**Comment by nfriend** [comment]
@JonathanWolfe This isn't a real solution, but I found renaming the file from `.gitlab-ci.yml` > `.gitlab-ci.yaml` fixed this issue.  So it seems that this extension is treating these extensions differently.  I'll try and find an existing issue or create a new one and link it here.

**Comment by JPinkney** [comment]
This should be fixed in 0.7.0!

**Comment by FelixBenning** [comment]
```
.ssh-script: &ssh-script
  before_script:
    - apt-get update && apt-get install -y -qq ssh
    - eval $(ssh-agent -s)
    - cat "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - cat ${HOST_PUBLIC_SSH_KEY} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

.ssh-dev-config: &ssh-dev-config
  image: ubuntu:latest
  variables: 
    HOST: ${DEV_SERVER_URL}
    HOST_PUBLIC_SSH_KEY: ${DEV_SERVER_SSH_ITS_PUBLIC_KEY}
    SSH_PRIVATE_KEY: ${DEV_SERVER_SSH_MY_PRIVATE_KEY}
  << : *ssh-script
```
Still getting the error `Property << is not allowed` with version 0.9.1
