### ISSUE TITLE
Auto-reload yaml schema if edited in the workspace

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-yaml#309]
when developing a yaml schema, it would be useful that when it is modified, the modified file is picked up automatically. Currently, I need to restart VS Code.

Use case:
- create a yaml schema
- modify settings yaml.schemas to point to it
- open a file X.yaml matching the glob pattern provided for yaml.schemas
- call completion in the X.yaml file
- modify the yaml schema, save
- go back to X.yaml editor
--> have completion/validation corresponding to the modified and saved yaml schema

**Comment by Morriz** [comment]
Just doing a window reload works as well, but that kills my bootstrapped shell (that holds many env settings), which is not nice.

**Comment by warthist** [comment]
Reloading the window after schema modifications shouldn't be the proper way of updating the validation. There should be an auto-reload mechanism upon schema change, or at least a command to reload schemas manually.

**Comment by runyontr** [comment]
As a workaround, if you remove the file manually from your `settings.json`, save it, and then add it back, VS will force reload the new schema on disk.

**Comment by Morriz** [comment]
I notice automatic reloading since a couple of weeks...so this is resolved imo

**Comment by corneliusroemer** [comment]
Not resolved for me here on Mac, also a duplicate has been opened after @Morriz comment: https://github.com/redhat-developer/vscode-yaml/issues/639

**Comment by LeShaunJ** [comment]
I can confirm the issue persists on Mac. Particularly when using the inline `# yaml-language-server: $schema=...` method. Current workaround for me is to (_tediously_):

1. Remove the inline comment.
   ```diff
   - # yaml-language-server: $schema=path/to/my.schema.json
     ---
     $schema: https://json-schema.org/draft-07/schema
   ```
3. Apply a random schema using schema-selector in the bottom right corner. 
   ![image](https://github.com/redhat-developer/vscode-yaml/assets/5474674/6e122fdf-6696-41a5-aaef-673fcd9f0e7a)
   and...
   ![image](https://github.com/redhat-developer/vscode-yaml/assets/5474674/e4b859a8-daef-438f-bd7f-997ac46f2a0d)
5. Re-adding the inline comment.
   ```diff
   + # yaml-language-server: $schema=path/to/my.schema.json
     ---
     $schema: https://json-schema.org/draft-07/schema
   ```

Not fun, nor ideal, when moving at a fast-pace.

**Comment by ProtocolNebula** [comment]
> I can confirm the issue persists on Mac. Particularly when using the inline `# yaml-language-server: $schema=...` method. Current workaround for me is to (_tediously_):


Same issue (Mac + # yaml-language server)

**Comment by jmbraben** [comment]
Same issue Ubuntu 22.04 with # yaml-language server

**Comment by Sibz** [comment]
Ran into same issue, I must reload window for changes to take effect. Can we get a command to clear schema cache please

**Comment by Sibz** [comment]
For those trying the same thing, I used the workaround mentioned, I use a local settings.json in the workspace for the schemas, I remove the "yaml.schemas" entry and replace it shortly after, for reference heres the script that does that from a VS Code extension:
```typescript
/**
 * Modifies the `yaml.schemas` entry in the `.vscode/settings.json` file within the workspace.
 *
 * This function performs the following steps:
 * 1. Checks if a workspace folder is open.
 * 2. Verifies the existence of the `.vscode/settings.json` file.
 * 3. Backs up the original `yaml.schemas` entry.
 * 4. Removes the `yaml.schemas` entry and saves the settings file.
 * 5. Waits for 500 milliseconds.
 * 6. Re-adds the original `yaml.schemas` entry and saves the settings file again.
 *
 * If any step fails, an appropriate error or warning message is shown to the user.
 */
function modifyYamlSchemas() {
  const workspaceRoot = vscode.workspace.workspaceFolders?.[0].uri.fsPath;
  if (!workspaceRoot) {
    vscode.window.showErrorMessage("No workspace folder is open.");
    return;
  }

  const settingsPath = path.join(workspaceRoot, ".vscode", "settings.json");

  // Check if the settings.json file exists
  if (!fs.existsSync(settingsPath)) {
    vscode.window.showErrorMessage("settings.json not found in .vscode folder.");
    return;
  }

  // Load the settings.json file
  const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));

  // Backup the original yaml.schemas entry
  const originalYamlSchemas = settings["yaml.schemas"];

  if (!originalYamlSchemas) {
    vscode.window.showWarningMessage("No yaml.schemas entry found in settings.json.");
    return;
  }

  // Remove yaml.schemas and save
  delete settings["yaml.schemas"];
  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
  vscode.window.showInformationMessage("yaml.schemas entry removed.");

  // Wait half a second before re-adding it
  setTimeout(() => {
    // Re-add the yaml.schemas entry and save
    settings["yaml.schemas"] = originalYamlSchemas;
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
    vscode.window.showInformationMessage("yaml.schemas entry re-added and settings.json updated.");
  }, 500); // Wait for 500 milliseconds
}
```

**Comment by apt-itude** [comment]
This issue still exists, but I discovered a much quicker version of [this workaround](https://github.com/redhat-developer/vscode-yaml/issues/309#issuecomment-1595007107) when using the `# yaml-language-server: $schema=` comment: simply pick a random schema from the selector on the bottom-right. The extension will automatically switch back to the specified schema from the comment and reload it in the process.
